export const LOGIN_START = "LOGIN START";
export const LOGIN_SUCCESS = "LOGIN SUCCESS";
export const LOGIN_FAILED = "LOGIN FAILED";

export const LOGOUT_START = "LOGOUT START";
export const LOGOUT_SUCCESS = "LOGOUT SUCCESS";
export const LOGOUT_FAILED = "LOGOUT FAILED";

export const GET_USER_START = "GET USER START";
export const SET_USER = "SET USER";
export const GET_USER_FAILED = "GET USER FAILED";

export const FIRST_TIME_APP_LOADED = "FIRST TIME APP LOADED";

export const LOAD_STALL_ITEMS_START = "LOAD STALL ITEMS START"
export const LOAD_STALL_ITEMS_SUCCESS = "LOAD STALL ITEMS SUCCESS";
export const LOAD_STALL_ITEMS_FAILED = "LOAD STALL ITEMS FAILED";